(()=>{'use strict';
const MODEL_URL='https://threejs.org/examples/models/gltf/Soldier.glb';
const FALLBACK_MODEL='https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/CesiumMan/glTF-Binary/CesiumMan.glb';
const canvas=document.getElementById('renderCanvas');
const scene=new THREE.Scene();scene.background=new THREE.Color(0x071017);scene.fog=new THREE.Fog(0x071017,28,95);
const camera=new THREE.PerspectiveCamera(45,innerWidth/innerHeight,.1,180);camera.position.set(0,3.8,14.5);
const renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputEncoding=THREE.sRGBEncoding;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;
scene.add(new THREE.HemisphereLight(0xbad9ff,0x172014,1.35));const key=new THREE.DirectionalLight(0xffffff,2.7);key.position.set(12,18,8);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.camera.left=-30;key.shadow.camera.right=30;key.shadow.camera.top=25;key.shadow.camera.bottom=-15;scene.add(key);for(let i=0;i<4;i++){const l=new THREE.PointLight(0xbfd9ff,2.8,38);l.position.set((i<2?-1:1)*(12+(i%2)*8),10,-25-(i%2)*12);scene.add(l)}
const mats={grass:new THREE.MeshStandardMaterial({color:0x16753a,roughness:.9}),line:new THREE.MeshStandardMaterial({color:0xf3f6f0,roughness:.65}),goal:new THREE.MeshStandardMaterial({color:0xf4f7f9,metalness:.15,roughness:.35}),net:new THREE.MeshStandardMaterial({color:0xdbe6e8,transparent:true,opacity:.3,side:THREE.DoubleSide}),stand:new THREE.MeshStandardMaterial({color:0x17232b,roughness:1}),crowd:[]};[0xd7ff42,0xf4f7f9,0x4f79a7,0xe65a44,0x8b5cf6,0xffb703].forEach(c=>mats.crowd.push(new THREE.MeshStandardMaterial({color:c,roughness:.85})));
function box(w,h,d,x,y,z,m,rx=0){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.position.set(x,y,z);o.rotation.x=rx;o.receiveShadow=true;o.castShadow=true;scene.add(o);return o}function cyl(r,h,x,y,z,m){const o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,32),m);o.position.set(x,y,z);o.receiveShadow=true;o.castShadow=true;scene.add(o);return o}
box(36,.25,82,0,-.15,-27,mats.grass);box(38,4,12,0,2,-58,mats.stand);box(38,4,12,0,2,4,mats.stand);for(let x=-17;x<=17;x+=2){for(let z=-62;z<=7;z+=3.1)cyl(.18,.42,x,4.35,z,mats.crowd[(Math.abs(x+z*3)|0)%mats.crowd.length])}for(const x of [-9,9])box(.035,.03,70,x,.01,-27,mats.line);for(const z of [-55,-39,-23,-7])box(18,.03,.08,0,.02,z,mats.line);
function goal(){box(12.1,.18,.18,0,5.1,-28,mats.goal);box(.18,5.2,.18,-6,2.5,-28,mats.goal);box(.18,5.2,.18,6,2.5,-28,mats.goal);box(.18,.18,5.5,-6,2.5,-30.7,mats.goal);box(.18,.18,5.5,6,2.5,-30.7,mats.goal);for(let x=-6;x<=6;x++)box(.018,5,.018,x,2.5,-30.7,mats.net);for(let y=0;y<=5;y+=.8)box(12,.018,.018,0,y,-30.7,mats.net)}goal();
const ball=new THREE.Mesh(new THREE.SphereGeometry(.43,32,20),new THREE.MeshStandardMaterial({color:0xf4f4ef,roughness:.28}));ball.position.set(0,.45,0);ball.castShadow=true;scene.add(ball);
const loader=new THREE.GLTFLoader(),mixers=[];let player=null,keeper=null,phase='menu',round=0,score=0,streak=0,charge=0,charging=false,aimX=0,aimY=.45,shot=null,last=performance.now();
function fit(root,h){const b=new THREE.Box3().setFromObject(root),s=h/(b.max.y-b.min.y);root.scale.multiplyScalar(s);const b2=new THREE.Box3().setFromObject(root);root.position.y-=b2.min.y}
function styleCharacter(root,role){const team=role==='keeper'?new THREE.Color(0x1769ff):new THREE.Color(0x123b9a);root.traverse(o=>{if(!o.isMesh)return;o.castShadow=true;o.receiveShadow=true;const n=(o.name+' '+(o.material?.name||'')).toLowerCase();if(o.material){o.material=o.material.clone();if(o.material.map)o.material.map.colorSpace=THREE.SRGBColorSpace||o.material.map.colorSpace;if(/skin|body|face|head|arm|leg/.test(n)){if(!o.material.map)o.material.color=new THREE.Color(0xc9825b)}else if(/hair/.test(n))o.material.color=new THREE.Color(0x17120f);else if(/eye|pupil/.test(n))o.material.color=new THREE.Color(0x17202a);else if(/shoe|boot/.test(n))o.material.color=new THREE.Color(0x111827);else if(/shirt|jersey|uniform|top|vest|pants|trouser/.test(n))o.material.color=team;else if(!o.material.map)o.material.color=new THREE.Color(0xf5f7fa)}})}
function loadUrl(url,role){return new Promise((res,rej)=>{let done=false;const finish=(fn,v)=>{if(done)return;done=true;clearTimeout(timer);fn(v)};const timer=setTimeout(()=>finish(rej,new Error('GLB timeout')),10000);loader.load(url,g=>{const r=g.scene;fit(r,role==='keeper'?2.35:2.25);r.position.set(0,0,role==='keeper'?-27.7:-2);r.rotation.y=Math.PI;styleCharacter(r,role);scene.add(r);const mix=new THREE.AnimationMixer(r);mixers.push(mix);if(g.animations[0])mix.clipAction(g.animations[0]).play();finish(res,{r,mix,clips:g.animations})},undefined,e=>finish(rej,e))})}
async function load(role){try{return await loadUrl(MODEL_URL,role)}catch(e){console.warn('Primary GLB failed, using fallback',e);return await loadUrl(FALLBACK_MODEL,role)}}
function ui(id,v){const e=document.getElementById(id);if(e)e.textContent=v}function show(id,on){const e=document.getElementById(id);if(e)e.classList.toggle('hidden',!on)}function setMenu(on){show('menu',on)}
function start(){phase='aim';round=0;score=0;streak=0;setMenu(false);show('hud',true);ui('score','0');ui('streak','0');ui('round','1 / 10');resetShot()}
function resetShot(){charging=false;charge=0;aimX=0;aimY=.45;ball.position.set(0,.45,0);if(player){player.r.position.set(0,0,-2);player.r.rotation.y=Math.PI}if(keeper){keeper.r.position.set(0,0,-27.7);keeper.r.rotation.y=Math.PI}phase='aim'}
function shoot(){if(phase!=='aim')return;phase='shot';const p=charge;shot={t:0,dur:.72+.3*(1-p),sx:0,sy:.45,sz:0,tx:aimX*4.8,ty:.45+aimY*4.2,tz:-29.3}}
function resolve(){const s=shot,save=Math.abs(s.tx)<2.6&&s.ty<3.8&&Math.random()<.48,goalIn=!save&&s.ty<4.9&&Math.abs(s.tx)<5.8;if(goalIn){score++;streak++;ui('score',score);ui('streak',streak)}else streak=0;if(keeper)keeper.r.position.x=THREE.MathUtils.clamp(save?s.tx*.35:s.tx*.05,-4.8,4.8);setTimeout(()=>{round++;if(round>=10){phase='end';show('hud',false);show('menu',true)}else{ui('round',`${round+1} / 10`);resetShot()}},900)}
function update(dt){mixers.forEach(m=>m.update(dt));if(phase==='aim'&&charging){charge=Math.min(1,charge+dt*1.35);ui('power',`${Math.round(charge*100)}%`);const b=document.getElementById('powerBar');if(b)b.style.width=`${charge*100}%`}if(phase==='shot'&&shot){shot.t+=dt;const q=Math.min(1,shot.t/shot.dur),e=1-Math.pow(1-q,3);ball.position.x=THREE.MathUtils.lerp(shot.sx,shot.tx,e);ball.position.y=THREE.MathUtils.lerp(shot.sy,shot.ty,e)+Math.sin(q*Math.PI)*.8;ball.position.z=THREE.MathUtils.lerp(shot.sz,shot.tz,e);ball.rotation.x-=dt*8;ball.rotation.z+=dt*6;if(q>=1){phase='result';resolve()}}}
function pointer(x,y){const r=canvas.getBoundingClientRect();aimX=((x-r.left)/r.width-.5)*2;aimY=THREE.MathUtils.clamp((1-(y-r.top)/r.height)*1.15-.3,-.15,1.15)}
addEventListener('pointermove',e=>{if(phase==='aim')pointer(e.clientX,e.clientY)});addEventListener('pointerdown',()=>{if(phase==='aim'){charging=true;charge=0}});addEventListener('pointerup',()=>{if(phase==='aim'&&charging)shoot()});addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();if(phase==='aim'){if(charging)shoot();else{charging=true;charge=0}}}});addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
const startBtn=document.getElementById('startBtn');if(startBtn)startBtn.onclick=start;
async function init(){ui('loadingText','Loading realistic animated GLB player…');try{player=await load('player');ui('loadingText','Loading goalkeeper GLB…');keeper=await load('keeper');ui('loadingText','READY');setTimeout(()=>{show('loading',false);setMenu(true)},400)}catch(e){console.error(e);ui('loadingText','Unable to load GLB. Refresh and try again.');setTimeout(()=>{show('loading',false);setMenu(true)},1500)}}
function loop(now){const dt=Math.min(.05,(now-last)/1000);last=now;update(dt);renderer.render(scene,camera);requestAnimationFrame(loop)}init();requestAnimationFrame(loop);
})();