(()=>{'use strict';
const MODEL_URL='https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/CesiumMan/glTF-Binary/CesiumMan.glb';
const canvas=document.getElementById('renderCanvas');
const scene=new THREE.Scene();scene.background=new THREE.Color(0x071017);scene.fog=new THREE.FogExp2(0x071017,.018);
const camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.05,220);const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.outputEncoding=THREE.sRGBEncoding;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;
const clock=new THREE.Clock(),sceneRoot=new THREE.Group();scene.add(sceneRoot),sceneRoot.name='CinematicPenaltyStadium';const loader=new THREE.GLTFLoader();const mixers=[];
let player,keeper,playerMixer,keeperMixer,ball,ballShadow,keeperHome=new THREE.Vector3(),shot=null,state='menu',charging=false,power=0,chargeDir=1,aimX=0,aimY=0,score=0,shots=0,goals=0,streak=0,round=1,paused=false,audioCtx=null;
const id=x=>document.getElementById(x),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function M(c,r=.7,m=0){return new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m})}function box(w,h,d,m){let x=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);x.castShadow=x.receiveShadow=true;return x}function cyl(r,h,m){let x=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,20),m);x.castShadow=x.receiveShadow=true;return x}
const pitch=box(68,.18,45,M(0x16753a,1));pitch.position.set(0,-.1,-13);scene.add(pitch);const white=M(0xf3f6f0,.45);function line(w,d,x,z){let l=box(w,.025,d,white);l.position.set(x,.015,z);scene.add(l)}line(68,.08,0,-35.5);line(68,.08,0,9.5);line(.08,45,-34,-13);line(.08,45,34,-13);line(16.5,.08,0,-19.5);line(16.5,.08,0,9.5);line(.08,29,-16.5,-5);line(.08,29,16.5,-5);
let spot=new THREE.Mesh(new THREE.CircleGeometry(.13,24),new THREE.MeshBasicMaterial({color:0xffffff}));spot.rotation.x=-Math.PI/2;spot.position.set(0,.03,-.1);scene.add(spot);
const goal=new THREE.Group();goal.position.set(0,0,-29.7);scene.add(goal);const post=M(0xf4f7f9,.22,.15);[-5.4,5.4].forEach(x=>{let p=cyl(.11,3.8,post);p.position.set(x,1.9,0);goal.add(p)});let bar=cyl(.11,10.8,post);bar.rotation.z=Math.PI/2;bar.position.y=3.8;goal.add(bar);let net=new THREE.Mesh(new THREE.BoxGeometry(10.8,3.8,2.3),new THREE.MeshBasicMaterial({color:0xdbe6e8,transparent:true,opacity:.16,wireframe:true}));net.position.set(0,1.9,1.15);goal.add(net);
for(let row=0;row<7;row++){let r=box(80,.5,2.2,M(0x17232b,1));r.position.set(0,1+row*.65,-22-row*1.8);scene.add(r);let r2=r.clone();r2.position.z=14+row*1.6;scene.add(r2)}
const crowdColors=[0xd7ff42,0xf4f7f9,0x4f79a7,0xe65a44,0x8b5cf6];for(let i=0;i<900;i++){let side=Math.random()<.5?-1:1,x,z,y;if(Math.random()<.5){x=(Math.random()-.5)*74;z=side<0?-38-Math.random()*11:13+Math.random()*11}else{x=side*(36+Math.random()*10);z=-34+Math.random()*42}y=2+Math.random()*5;let q=new THREE.Mesh(new THREE.SphereGeometry(.045+Math.random()*.07,5,5),new THREE.MeshBasicMaterial({color:crowdColors[i%5]}));q.position.set(x,y,z);scene.add(q)}
scene.add(new THREE.HemisphereLight(0xa9c7ff,0x12351f,1.7));let sun=new THREE.DirectionalLight(0xffffff,3.4);sun.position.set(-18,34,8);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-45;sun.shadow.camera.right=45;sun.shadow.camera.top=40;sun.shadow.camera.bottom=-45;scene.add(sun);[-25,25].forEach(x=>{let l=new THREE.SpotLight(0xffffff,65,90,Math.PI/7,.45,1.2);l.position.set(x,22,-8);l.target.position.set(0,0,-18);scene.add(l,l.target)});
ball=new THREE.Mesh(new THREE.SphereGeometry(.34,32,20),M(0xf4f4ef,.38,.02));ball.castShadow=true;ball.position.set(0,.37,-.1);scene.add(ball);ballShadow=new THREE.Mesh(new THREE.CircleGeometry(.5,24),new THREE.MeshBasicMaterial({color:0x000000,transparent:true,opacity:.25}));ballShadow.rotation.x=-Math.PI/2;ballShadow.position.set(0,.025,-.1);scene.add(ballShadow);
function fit(root,h){let b=new THREE.Box3().setFromObject(root),s=h/(b.max.y-b.min.y);root.scale.setScalar(s);b.setFromObject(root);root.position.y-=b.min.y}function tint(root,c){root.traverse(o=>{if(o.isMesh){o.castShadow=o.receiveShadow=true;if(o.material){o.material=o.material.clone();o.material.color=new THREE.Color(c);o.material.roughness=.72}}})}
function load(role){return new Promise((res,rej)=>loader.load(MODEL_URL,g=>{let r=g.scene;fit(r,role==='keeper'?2.35:2.25);r.position.set(0,0,role==='keeper'?-27.7:-2);r.rotation.y=Math.PI;tint(r,role==='keeper'?0x3b72ff:0xf1f1f1);scene.add(r);let mix=new THREE.AnimationMixer(r);mixers.push(mix);if(g.animations[0])mix.clipAction(g.animations[0]).play();res({r,mix})},p=>{if(role==='player')id('loadBar').style.width=(10+Math.round((p.loaded/(p.total||p.loaded))*50))+'%'},rej))}
async function init(){try{id('loadText').textContent='Loading animated GLB footballer…';let p=await load('player');player=p.r;playerMixer=p.mix;id('loadBar').style.width='68%';id('loadText').textContent='Loading goalkeeper GLB…';let k=await load('keeper');keeper=k.r;keeperMixer=k.mix;keeperHome.copy(keeper.position);id('loadBar').style.width='100%';id('loadText').textContent='Finalizing stadium lighting…';setTimeout(()=>{id('loading').classList.add('hidden');id('menu').classList.remove('hidden');menuCamera()},500)}catch(e){console.error(e);id('loadText').textContent='GLB load failed — check network access.'}}
function menuCamera(){camera.position.set(11,7,7);camera.lookAt(0,1,-18)}function gameCamera(){camera.position.set(0,3.05,4.9);camera.lookAt(0,1.7,-20)}
function hud(){id('score').textContent=score;id('streak').textContent=streak;id('roundLabel').textContent='PENALTY '+String(round).padStart(2,'0');id('powerValue').textContent=Math.round(power*100)+'%';id('powerBar').style.width=power*100+'%'}function result(t){let r=id('result');r.textContent=t;r.classList.remove('show');void r.offsetWidth;r.classList.add('show')}
function aim(x,y){let r=canvas.getBoundingClientRect();aimX=clamp((x-r.left)/r.width*2-1,-1,1);aimY=clamp(-((y-r.top)/r.height*2-1),-.72,.72);let a=document.querySelector('.aim');a.style.left=50+aimX*30+'%';a.style.top=50-aimY*24+'%'}
function charge(){if(state!=='play'||paused||shot)return;if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();charging=true}function shoot(){if(!charging||state!=='play'||shot)return;charging=false;power=Math.max(.18,power);fire()}
function fire(){shots++;let end=new THREE.Vector3(aimX*5,1.05+aimY*2,-29);shot={t:0,dur:1.08,power,start:ball.position.clone(),end,arc:.8+power*1.7};hud();kick()}
function kick(){if(!audioCtx)return;let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='triangle';o.frequency.setValueAtTime(130,audioCtx.currentTime);o.frequency.exponentialRampToValueAtTime(55,audioCtx.currentTime+.18);g.gain.setValueAtTime(.05,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.22);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.23)}
function whistle(){if(!audioCtx)return;let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=1100;g.gain.value=.025;o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.18)}
function evaluate(){let s=shot,inside=Math.abs(s.end.x)<5.2&&s.end.y>.2&&s.end.y<3.7,reach=2.15+Math.min(.35,round*.03),dist=Math.hypot(s.end.x-keeper.position.x,s.end.y-1.1);let saved=inside&&dist<reach&&Math.random()<.82,goal=inside&&!saved&&Math.random()>.045;if(goal){goals++;streak++;score+=Math.round(100+power*180+Math.max(0,streak-1)*25);result(streak>=3?'ON FIRE':'GOAL')}else{streak=0;result(saved?'SAVED':'MISS')}round++;hud();whistle();setTimeout(next,1150)}function next(){shot=null;power=0;ball.position.set(0,.37,-.1);keeper.position.copy(keeperHome);if(round>10)finish();hud()}
function finish(){state='end';id('hud').classList.add('hidden');id('end').classList.remove('hidden');id('finalScore').textContent=score;id('finalShots').textContent=shots;id('finalGoals').textContent=goals;id('finalAccuracy').textContent=(shots?Math.round(goals/shots*100):0)+'%';id('endTitle').textContent=goals>=7?'ELITE FINISH':goals>=5?'GREAT SHOOTOUT':'KEEP TRAINING'}
function start(){state='play';paused=false;score=shots=goals=streak=0;round=1;power=0;shot=null;ball.position.set(0,.37,-.1);keeper.position.copy(keeperHome);id('menu').classList.add('hidden');id('end').classList.add('hidden');id('hud').classList.remove('hidden');gameCamera();hud()}
function pause(v){if(state!=='play')return;paused=v===undefined?!paused:v;id('pause').classList.toggle('hidden',!paused)}
canvas.addEventListener('pointermove',e=>aim(e.clientX,e.clientY));canvas.addEventListener('pointerdown',e=>{aim(e.clientX,e.clientY);charge()});window.addEventListener('pointerup',shoot);window.addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();charge()}if(e.code==='Escape')pause()});window.addEventListener('keyup',e=>{if(e.code==='Space')shoot()});id('playBtn').onclick=start;id('pauseBtn').onclick=()=>pause();id('resumeBtn').onclick=()=>pause(false);id('menuBtn').onclick=()=>{state='menu';id('pause').classList.add('hidden');id('hud').classList.add('hidden');id('menu').classList.remove('hidden');menuCamera()};id('againBtn').onclick=start;id('endMenuBtn').onclick=()=>{state='menu';id('end').classList.add('hidden');id('menu').classList.remove('hidden');menuCamera()};
function frame(dt){if(!paused){mixers.forEach(m=>m.update(dt));if(state==='play'){if(charging&&!shot){power+=dt*.72*chargeDir;if(power>=1){power=1;chargeDir=-1}if(power<=0){power=0;chargeDir=1}hud()}if(shot){shot.t+=dt/shot.dur;let q=clamp(shot.t,0,1),e=q*q*(3-2*q);ball.position.lerpVectors(shot.start,shot.end,e);ball.position.y+=Math.sin(q*Math.PI)*shot.arc;ball.rotation.x-=dt*12;ball.rotation.z+=dt*8;ballShadow.position.x=ball.position.x;ballShadow.position.z=ball.position.z;if(q>=1)evaluate()}}else if(state==='menu'){camera.position.x=11+Math.sin(performance.now()*.00015)*2;camera.lookAt(0,1,-18)}}renderer.render(scene,camera);requestAnimationFrame(()=>frame(Math.min(.033,clock.getDelta())))}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2))});init();frame(0);
})();
